apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sumrender/deployment-basics-configuration.git
    targetRevision: main
    path: k8s/staging
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
