apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
  labels:
    app: mongo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongo

